Repository csi-addons/kubernetes-csi-addons, pull requests merged in 2023-06, with the labels that each got.

#386 ci: include `/tools` directory in dependabot config
  .github/dependabot.yml
Labels: vendor

#385 Adding version details to sidecar
  Makefile
  cmd/manager/main.go
  internal/version/version.go
  sidecar/main.go
Labels: enhancement

#398 cleanup: corrections in the ci doc
  docs/ci.md
Labels: documentation
